version: 1.0.{build}
skip_non_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_folder: c:\projects\fake-implementation
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: Fake Implementation.sln
  verbosity: minimal
after_build:
- cmd: >-
    7z a -tzip -r -y "C:\projects\fake-implementation\FakeImplementation.zip" "c:\projects\fake-implementation\FakeImplementation\bin\Release\*.exe" "c:\projects\fake-implementation\FakeImplementation\bin\Release\*.dll"
    7z a -tzip -r -y "C:\projects\fake-implementation\FakeImplementation.Cecil.zip" "c:\projects\fake-implementation\FakeImplementation.Cecil\bin\Release\*.exe" "c:\projects\fake-implementation\FakeImplementation.Cecil\bin\Release\*.dll"
    appveyor PushArtifact "FakeImplementation.zip"
    appveyor PushArtifact "FakeImplementation.Cecil.zip"
test: off
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: Fake Implementation $(appveyor_build_version)
  auth_token:
    secure: eB/f/gaHNdbnJ+OnBkLczo2r4yU4272Gt8/eSSJTZofSYDh30GhB3Y9cQPvAzQRA
  draft: true
  force_update: true
  on:
    branch: master