version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\projects\fake-implementation
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: quiet
test: off
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: Fake Implementation $(appveyor_build_version)
  auth_token:
    secure: eB/f/gaHNdbnJ+OnBkLczo2r4yU4272Gt8/eSSJTZofSYDh30GhB3Y9cQPvAzQRA
  draft: true
  force_update: true
  on:
    branch: master